### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by nikich340** [Komosa/cf#4]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0xc15623]

goroutine 1 [running]:
github.com/andybalholm/cascadia.tagSelector.Match(...)
        /home/przemek/go/src/github.com/andybalholm/cascadia/selector.go:217
github.com/andybalholm/cascadia.compoundSelector.Match(0xc000004740, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc00010fc00)
        /home/przemek/go/src/github.com/andybalholm/cascadia/selector.go:813 +0x76
github.com/andybalholm/cascadia.SelectorGroup.Match(0xc000046ce0, 0x1, 0x1, 0x0, 0xc00010fcf0)
        /home/przemek/go/src/github.com/andybalholm/cascadia/selector.go:933 +0x6f
github.com/andybalholm/cascadia.Selector.matchAllInto(0xc000004760, 0x0, 0x0, 0x0, 0x0, 0xc00008e000, 0x0, 0x0)
        /home/przemek/go/src/github.com/andybalholm/cascadia/selector.go:128 +0x3b
github.com/andybalholm/cascadia.Selector.MatchAll(...)
        /home/przemek/go/src/github.com/andybalholm/cascadia/selector.go:124
main.(*cf).login(0xc00010fef0, 0xc00000a0d0, 0x9, 0xc00000cc40, 0x11, 0x0, 0x0)
        /home/przemek/go/src/github.com/Komosa/cf/login.go:37 +0x31e
main.run(0xc1cdfb, 0xca45d6)
        /home/przemek/go/src/github.com/Komosa/cf/main.go:78 +0x41b
main.main()
        /home/przemek/go/src/github.com/Komosa/cf/main.go:39 +0x2d

**Comment by pkitszel** [comment]
It looks like CF webpage were changed/malfunctioning 4 weeks ago. Logging now works OK for me.
@nikich340, please recheck.
